services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

  typesense:
    image: typesense/typesense:30.2
    restart: unless-stopped
    ports:
      - "8108:8108"
    command:
      - "--data-dir=/data"
      - "--api-key=${TYPESENSE_ADMIN_API_KEY}"
      - "--enable-cors"
    volumes:
      - typesense-data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8108/health || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  redis-data:
  typesense-data: